# Generated by Django 5.1.3 on 2024-11-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_stat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresult',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
