# Generated by Django 5.1.3 on 2024-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_stat', '0002_alter_queryresult_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresult',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
